version: '3.8'

services:
  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: formflow
      POSTGRES_USER: formflow
      POSTGRES_PASSWORD: root1234

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://formflow:root1234@db:5432/formflow
      - CELERY_BROKER_URL=redis://redis:6379/0

  celery:
    build: .
    command: celery -A myproject worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=postgres://formflow:root1234@db:5432/formflow
      - CELERY_BROKER_URL=redis://redis:6379/0

  celery-beat:
    build: .
    command: celery -A myproject beat --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=postgres://formflow:root1234@db:5432/formflow
      - CELERY_BROKER_URL=redis://redis:6379/0

  redis:
    image: redis:7

volumes:
  postgres_data:
