# Generated by Django 5.0.8 on 2024-08-10 00:39

import core.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('type', models.CharField(choices=[('TE', 'تشریحی'), ('RA', 'نظرسنجی'), ('MC', 'چند گزینه ای'), ('MX', 'ماتریسی')], default='TE', max_length=20)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', core.models.Manager()),
                ('alives', core.models.DeletableAliveManager()),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('title', models.CharField(default=None, max_length=250, null=True)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('TE', 'تشریحی'), ('RA', 'نظرسنجی'), ('MC', 'چند گزینه ای'), ('MX', 'ماتریسی')], default='TE', max_length=20)),
                ('is_required', models.BooleanField(default=False)),
                ('order', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', core.models.Manager()),
                ('alives', core.models.DeletableAliveManager()),
            ],
        ),
        migrations.CreateModel(
            name='MatrixAnswer',
            fields=[
                ('answer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='survey.answer')),
                ('answer_value', models.JSONField()),
            ],
            options={
                'abstract': False,
            },
            bases=('survey.answer',),
            managers=[
                ('objects', core.models.Manager()),
                ('alives', core.models.DeletableAliveManager()),
            ],
        ),
        migrations.CreateModel(
            name='MultipleChoiceAnswer',
            fields=[
                ('answer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='survey.answer')),
                ('answer_value', models.JSONField()),
            ],
            options={
                'abstract': False,
            },
            bases=('survey.answer',),
            managers=[
                ('objects', core.models.Manager()),
                ('alives', core.models.DeletableAliveManager()),
            ],
        ),
        migrations.CreateModel(
            name='RatingAnswer',
            fields=[
                ('answer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='survey.answer')),
                ('answer_value', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
            bases=('survey.answer',),
            managers=[
                ('objects', core.models.Manager()),
                ('alives', core.models.DeletableAliveManager()),
            ],
        ),
        migrations.CreateModel(
            name='TextAnswer',
            fields=[
                ('answer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='survey.answer')),
                ('answer_value', models.TextField()),
            ],
            options={
                'abstract': False,
            },
            bases=('survey.answer',),
            managers=[
                ('objects', core.models.Manager()),
                ('alives', core.models.DeletableAliveManager()),
            ],
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField(default=None, null=True)),
                ('subject', models.CharField(default='General', max_length=250)),
                ('status', models.CharField(choices=[('DR', 'پیش نویس'), ('PU', 'منتشر شده'), ('AR', 'بایگانی شده'), ('DE', 'حذف شده')], default='DR', max_length=2)),
                ('availability', models.CharField(choices=[('OP', ''), ('CL', ''), ('RS', '')], default='OP', max_length=2)),
                ('published_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('archived_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forms', related_query_name='form', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', core.models.Manager()),
                ('alives', core.models.DeletableAliveManager()),
            ],
        ),
        migrations.CreateModel(
            name='MatrixQuestion',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='survey.question')),
                ('rows', models.JSONField(default=list)),
                ('columns', models.JSONField(default=list)),
            ],
            options={
                'abstract': False,
            },
            bases=('survey.question',),
            managers=[
                ('objects', core.models.Manager()),
                ('alives', core.models.DeletableAliveManager()),
            ],
        ),
        migrations.CreateModel(
            name='MultipleChoiceQuestion',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='survey.question')),
                ('allow_multiple', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
            bases=('survey.question',),
            managers=[
                ('objects', core.models.Manager()),
                ('alives', core.models.DeletableAliveManager()),
            ],
        ),
        migrations.CreateModel(
            name='RatingQuestion',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='survey.question')),
                ('min_rating', models.IntegerField(default=1)),
                ('max_rating', models.IntegerField(default=5)),
            ],
            options={
                'abstract': False,
            },
            bases=('survey.question',),
            managers=[
                ('objects', core.models.Manager()),
                ('alives', core.models.DeletableAliveManager()),
            ],
        ),
        migrations.CreateModel(
            name='TextQuestion',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='survey.question')),
            ],
            options={
                'abstract': False,
            },
            bases=('survey.question',),
            managers=[
                ('objects', core.models.Manager()),
                ('alives', core.models.DeletableAliveManager()),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='form',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', related_query_name='question', to='survey.form'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', related_query_name='answer', to='survey.question'),
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('ip_address', models.CharField(default=None, max_length=15, null=True)),
                ('status', models.CharField(choices=[('DR', 'پیش نویس'), ('PU', 'منتشر شده'), ('AR', 'بایگانی شده')], default='DR', max_length=2)),
                ('creator', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responses', related_query_name='response', to=settings.AUTH_USER_MODEL)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', related_query_name='response', to='survey.form')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', core.models.Manager()),
                ('alives', core.models.DeletableAliveManager()),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='response',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', related_query_name='answer', to='survey.response'),
        ),
    ]
