# Generated by Django 5.0.8 on 2024-08-11 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='multiplechoicequestion',
            name='choices',
            field=models.JSONField(default=None),
            preserve_default=False,
        ),
    ]
